site_name: CosmoLattice World #Manual#
repo_url: https://github.com/cosmolattice/cosmolattice

theme:
  name: material
  features:
    - content.code.copy
    - content.code.select
    - navigation.tabs
    - navigation.path
    - navigation.indexes
    - toc.integrate
  logo: assets/CL_Icon.png
  favicon: assets/CL_Icon.png
  palette:
    primary: white
    accent: light blue
  icon:
    repo: fontawesome/brands/git-alt
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left

plugins:
  - bibtex:
      bib_file: "refs.bib"
  - mkdoxy:
      projects:
        CosmoLattice: # name of project must be alphanumeric + numbers (without spaces)
          src-dirs: ../tmp/code_source/templat/include ../tmp/code_source/cosmolattice/include # path to source code (support multiple paths separated by space) => INPUT
          full-doc: True # if you want to generate full documentation
          doxy-cfg: # standard doxygen configuration (key: value)
            FILE_PATTERNS: "*.cpp *.h" # specify file patterns to filter out
            STRIP_FROM_PATH: ../../
            RECURSIVE: True # recursive search in source directories
      full-doc: True # if you want to generate full documentation
  - search
  - autorefs
  - offline
  - gen-files:
      scripts:
        - exclusions.py

markdown_extensions:
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  #- markdown_katex:
  #    no_inline_svg: True
  #    insert_fonts_css: True
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format:
            !!python/object/apply:pymdownx.arithmatex.arithmatex_fenced_format {
              kwds: { mode: generic },
            }

extra_javascript:
  - javascripts/mathjax.js
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/languages/cpp.min.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/emgithub-fixraw.js

extra_css:
  - extra.css
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/github.min.css

hooks:
  - hooks/resolve_emgithub.py

use_directory_urls: false # (optional) for better links without .html extension

nav:
  - Home: #CL.md
      - "<span style='font-weight:bold;'>CosmoLattice in a Nutshell</span>": "CL.md"
      - "<span style='font-weight:bold;'>If you use CosmoLattice </span>": "CLcitation.md"
      - "<span style='font-weight:bold;'>Latest News </span>": "CLnews.md"
  - Code: 
      #- "What is CosmoLattice": "code/HowToCiteCL.md"
      #- "How to cite CosmoLattice": "code/HowToCiteCL.md"
      - "Download": "code/Download.md"
      - "Features": "code/Features.md"
      - "Links": "code/index.md"
  - API:
      - "Links": "CosmoLattice/links.md"
      - "Classes":
          - "Class List": "CosmoLattice/annotated.md"
          - "Class Index": "CosmoLattice/classes.md"
          - "Class Hierarchy": "CosmoLattice/hierarchy.md"
          - "Class Members": "CosmoLattice/class_members.md"
          - "Class Member Functions": "CosmoLattice/class_member_functions.md"
          - "Class Member Variables": "CosmoLattice/class_member_variables.md"
          - "Class Member Typedefs": "CosmoLattice/class_member_typedefs.md"
          - "Class Member Enumerations": "CosmoLattice/class_member_enums.md"
      - "Namespaces":
          - "Namespace List": "CosmoLattice/namespaces.md"
          - "Namespace Members": "CosmoLattice/namespace_members.md"
          - "Namespace Member Functions": "CosmoLattice/namespace_member_functions.md"
          - "Namespace Member Variables": "CosmoLattice/namespace_member_variables.md"
          - "Namespace Member Typedefs": "CosmoLattice/namespace_member_typedefs.md"
          - "Namespace Member Enumerations": "CosmoLattice/namespace_member_enums.md"
      - "Functions": "CosmoLattice/functions.md"
      - "Variables": "CosmoLattice/variables.md"
      - "Macros": "CosmoLattice/macros.md"
      - "Files": "CosmoLattice/files.md"
  #- Technical Notes:#
  - Theory Framework:
      #- "Power spectra": "tech_notes/Power spectra.md"#
      #- "Gravitational Waves": "tech_notes/Gravitational waves.md"#
      #- "Gravitational Waves from U(1) Gauge Theories": "tech_notes/Gravitational waves from U(1) gauge theories.md"#
      - "<span style='font-size:0.85em; font-style:italic;'>Theory Framework Guide</span>": "th_framework/TF_readme.md"
      - "Monographic Reviews on LCT": "th_framework/MonographicReviews.md"
      - "Field Discretization Primer": "th_framework/Brief_Review_On_Lattice_Techniques.md"
      - "Technical Notes": "th_framework/TechnicalNotes.md"
      - "Technical Notes (online)":
        -  "Power Spectrum (Note I)": "th_framework/tech_notes/Power spectra.md"
        -  "GWs from Scalars (Note II)": "th_framework/tech_notes/Gravitational waves.md"
        -  "GWs from U(1) Scalar-Gauge theories (Note III)": "th_framework/tech_notes/Gravitational waves from U(1) gauge theories.md"
  - User Manual:
      - "<span style='font-weight:bold;'>About This Manual</span>": "Manual/About This Manual.md"
      - "<span style='font-size:0.85em; font-style:italic;'>&nbsp;&nbsp;&nbsp;&nbsp;- Quick installation and execution</span>": "Manual/Quick installation and execution.md"
      - "<span style='font-size:0.85em; font-style:italic;'>&nbsp;&nbsp;&nbsp;&nbsp;- Conventions and Notation</span>": "Manual/Conventions and Notation.md"
      - "<span style='font-size:0.85em; font-style:italic;'>&nbsp;&nbsp;&nbsp;&nbsp;- How to cite CosmoLattice</span>": "Manual/HowToCiteCL.md"
      #- "Overview": "Manual/Overview.md"
      - "<span style='font-weight:bold;'>Introduction to CosmoLattice</span>": "Manual/Introduction to CosmoLattice.md"
      - "<span style='font-weight:bold;'>Scalar Field Dynamics</span>": "Manual/My first model of (singlet) scalar fields.md"
      - "<span style='font-weight:bold;'>Scalar-Gauge Theories</span>": "Manual/My first model of gauge fields.md"
      #- "<span style='font-weight:bold;'>Non-Abelian Gauge Theories</span>": "Manual/My first model of gauge fields.md"#
      - "What CosmoLattice does in detail": "Manual/What CosmoLattice does in detail.md"
      - "Useful features: parallel support, backing up and others": "Manual/Useful features: parallel support, backing up and others.md"
      - "Acknowledgments": "Manual/Acknowledgments.md"
      - "Installation": "Manual/Installation.md"
      - "Appendix: Parameters": "Manual/Appendix: Parameters.md"
      - "Appendix: Generic Model variables": "Manual/Appendix: Generic Model variables.md"
      - "Appendix: CMake Flags": "Manual/Appendix: CMake Flags.md"
      - "List of Implemented Functions": "Manual/List of Implemented Functions.md"
      - "Under the Hood: Expression Templates and CosmoLattice": "Manual/Under the Hood: Expression Templates and CosmoLattice.md"
