#include "TempLat/lattice/algebra/operators/add.h"
#include "TempLat/lattice/algebra/operators/arg.h"
#include "TempLat/lattice/algebra/operators/subtract.h"
#include "TempLat/lattice/algebra/operators/multiply.h"
#include "TempLat/lattice/algebra/operators/divide.h"
#include "TempLat/lattice/algebra/operators/power.h"
#include "TempLat/lattice/algebra/operators/squareroot.h"
#include "TempLat/lattice/algebra/operators/cosine.h"
#include "TempLat/lattice/algebra/operators/heavisidestepfunction.h"
#include "TempLat/lattice/algebra/operators/absolutevalue.h"
#include "TempLat/lattice/algebra/operators/unaryminus.h"
#include "TempLat/lattice/algebra/operators/complexconjugate.h"
#include "TempLat/lattice/algebra/operators/tanh.h"
#include "TempLat/lattice/algebra/operators/cosh.h"
#include "TempLat/lattice/algebra/operators/sinh.h"
#include "TempLat/lattice/algebra/operators/asinh.h"
#include "TempLat/lattice/algebra/operators/log.h"
#include "TempLat/lattice/algebra/operators/exponential.h"


